### ISSUE TITLE
启动不了，之前有朋友说 吧120s 延长，我延长了12000s 似乎也不行， 

### ISSUE THREAD

**Issue by yangyz** [nobodyiam/apollo-build-scripts#10]
您好  
![image](https://user-images.githubusercontent.com/6257884/42363273-8b695e72-8129-11e8-80fe-2e33bcb7d9db.png)

![image](https://user-images.githubusercontent.com/6257884/42364606-48421bf2-812e-11e8-86d2-29e770b4afe9.png)

**Comment by yangyz** [comment]
![image](https://user-images.githubusercontent.com/6257884/42364736-cfa250d0-812e-11e8-8edb-8bea2aa9d691.png)
添加一个目录 日志就是  
![image](https://user-images.githubusercontent.com/6257884/42364744-dd84fb8a-812e-11e8-8542-86fb530dcf9e.png)
jar 不能打开 要不看看 168行 到底是什么鬼

**Comment by nobodyiam** [comment]
你是用的git bash吗？建议安装最新版本吧

**Comment by yangyz** [comment]
你好 解决了。 环境变量需配置 JAVA_HOME  且要重启电脑，非常感谢 ！
