### ISSUE TITLE
portal:系统出错,请重试或联系系统负责人

### ISSUE THREAD

**Issue by SugisakiKen** [nobodyiam/apollo-build-scripts#17]
在添加命名空间后,portal首页刷新显示:"系统出错,请重试或联系系统负责人"
打开web console 定位是:
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/23693530/48836982-23cd6580-edbf-11e8-9448-31a036a23bf1.png">

另外:./portal/apollo-portal.log中一直有(具体ip已替换):

org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://ip:8090/health": ip:8090 failed to respond; nested exception is org.apache.http.NoHttpResponseException: ip:8090 failed to respond

**Comment by nobodyiam** [comment]
健康检测失败，访问下 http://ip:8090/health 看看

**Comment by SugisakiKen** [comment]
> 健康检测失败，访问下 http://ip:8090/health 看看

{"status":{"code":"UP","description":"Spring Cloud Eureka Discovery Client"},"details":{"discoveryComposite":{"status":{"code":"UP","description":"Spring Cloud Eureka Discovery Client"},"details":{"discoveryClient":{"status":{"code":"UP","description":"Spring Cloud Eureka Discovery Client"},"details":{"services":["apollo-configservice","apollo-adminservice"]}}}},"diskSpace":{"status":{"code":"UP","description":""},"details":{"total":250685575168,"free":81777483776,"threshold":10485760}},"refreshScope":{"status":{"code":"UP","description":""},"details":{}},"hystrix":{"status":{"code":"UP","description":""},"details":{}}}}

**Comment by nobodyiam** [comment]
"系统出错,请重试或联系系统负责人"应该就是因为portal访问admin service的health接口失败
