### ISSUE TITLE
demo.sh may not work well sometimes

### ISSUE THREAD

**Issue by kezhenxu94** [nobodyiam/apollo-build-scripts#26]
Running the docker image may sometimes produces an error:

```text
/apollo-quick-start/demo.sh: ./service/apollo-service.jar: /bin/bash: bad interpreter: Text file busy
```

problem due to:

https://github.com/nobodyiam/apollo-build-scripts/blob/301d2e8e70485e8674d7046143befe1f9fac026d/demo.sh#L113-L115

it modifies the file and immediately executes it, adding a command `sync` after `chmod` solves the problem

> I have no time to send a pull request and wait for new docker image, so I fix this and build and push one on my own, if it's fixed I'll consider switching back to this **not so official** docker image

**Comment by nobodyiam** [comment]
it's the same as https://github.com/ctripcorp/apollo/issues/1450

**Comment by kezhenxu94** [comment]
> it's the same as [ctripcorp/apollo#1450](https://github.com/ctripcorp/apollo/issues/1450)

Oh, I didn't search in that repo, well it's the same, thanks
