### ISSUE TITLE
连接数据库的 ip？？

### ISSUE THREAD

**Issue by superstonne** [nobodyiam/apollo-build-scripts#36]
java.sql.SQLException: Access denied for user 'root'@'180.168.56.186' (using password: YES)

都不知道这个 ip 地址是怎么来的？我配的 数据库地址不是这个，这个地址哪里来的？有没有人同样的问题？百度网盘下载的jar包

**Comment by nobodyiam** [comment]
这个错误信息是说数据库拒绝了**来自180.168.56.186**的root帐号登录请求
