### ISSUE TITLE
demo启动报错

### ISSUE THREAD

**Issue by chenkd** [nobodyiam/apollo-build-scripts#44]
windows环境下启动报错![image](https://user-images.githubusercontent.com/23569147/74007361-1e0a7280-49b9-11ea-97f5-56c8e32dab76.png)
加上双引号之后可以正常运行
![image](https://user-images.githubusercontent.com/23569147/74007465-61fd7780-49b9-11ea-820d-b93c7696e4dc.png)

**Comment by nobodyiam** [comment]
该问题之前有类似的案例，是通过加双引号解决的吗？

**Comment by chenkd** [comment]
上述加双引号无法解决该问题。

日志中也会有此错误。![image](https://user-images.githubusercontent.com/23569147/74080418-e403a400-4a7e-11ea-947e-411c159db53c.png)

此问题原因是JAVA_HOME中带有空格，空格在bash中属于特殊符号。

修改JAVA_HOME可解决此问题。
![image](https://user-images.githubusercontent.com/23569147/74080439-26c57c00-4a7f-11ea-8388-623651298443.png)

**Comment by nobodyiam** [comment]
@chenkd 不是是不是git bash的版本比较老？我之前安装的较新版本的git bash，是支持把带空格的java home路径映射为不带空格的，就是图中cygpath那两段
