### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by mars00772** [nobodyiam/apollo-build-scripts#5]
cat ./service/apollo-service_rootservice.log 
start-stop-daemon: unrecognized option '--no-close'
Try 'start-stop-daemon --help' for more information.

**Comment by nobodyiam** [comment]
是什么os？

**Comment by mars00772** [comment]
原来需要在ubuntu 64bit上，14.04以上才能跑，因为all in one的jar包需要start-stop-daemon的--no-close参数，而

> --no-close is a parameter that was "recently" added to start-stop-daemon

**Comment by nobodyiam** [comment]
好的，多谢~
