### ISSUE TITLE
apollo-quick-start启动报错

### ISSUE THREAD

**Issue by wzg547228197** [nobodyiam/apollo-build-scripts#61]
启动报错
Config service failed to start in 120 seconds! Please check ./service/apollo-service.log for more information.

我去对应的日志文件里看到输出是这样的
/apollo-quick-start/service # cat apollo-service_apollo-quick-startservice.log
sh: -Dspring.datasource.username=root: not found
sh: -Dspring.datasource.username=root: not found

docker-compose.yml内容为
version: '2.1'

networks:
   default:
     name: apollo-latest

services:
    apollo-quick-start:
        image: nobodyiam/apollo-quick-start
        hostname: apollo-quick-start
        depends_on:
            - apollo-db
        links:
            - apollo-db
    apollo-db:
        image: mysql:5.7
        hostname: apollo-db
        volumes:
            - ./classes/docker/sql:/docker-entrypoint-initdb.d
        environment:
            - TZ=Asia/Shanghai
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes

**Comment by wzg547228197** [comment]
@nobodyiam

**Comment by nobodyiam** [comment]
镜像有点问题，已经重新提交了，把本地镜像清理一下，下载最新的吧

```bash
1. docker-compose rm
2. docker pull nobodyiam/apollo-quick-start:latest
3. docker-compose up
```

**Comment by wzg547228197** [comment]
可以了，感谢
